# Generated by Django 4.0.2 on 2022-02-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Value', max_length=5000)),
                ('contenido', models.TextField(default='value')),
                ('img_destacada', models.FileField(upload_to='')),
                ('slug', models.CharField(default='value', max_length=5000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
